language: ruby

sudo: false

addons:
  apt:
    sources:
    - git-core
    packages:
    - git

install:
  - true

script:
  - true

deploy:
  provider: atlas
  token: foo
  app: bar
  include:
    - baz
  edge:
    branch: sol-atlas-debug
  on:
    all_branches: true

notifications:
  email: false
# raw git clone
