language: node_js
sudo: false

before_install:
  - curl -O https://raw.githubusercontent.com/yrashk/kerl/master/kerl
  - chmod +x kerl
  - ./kerl build 18.1 18.1
  - ./kerl install 18.1 ~/erlang/18.1
  - . ~/erlang/18.1/activate
script:
  - erl -v
